### ISSUE TITLE
Cannot allocate memory in docker image

### ISSUE THREAD

**Issue by flammie** [meertensinstituut/mtas#1]
We have been testing the ISO/TEI mtas using your docker image, currently it systematically dies after a bit of use and solr fails to restart with "Unable to allocate memory" error. Do you know if this is only due to fact that our testing environment is a rather limited and over-used virtual server, or if there's something in the setup that needs changing? I tried changing the /opt/solr/bin/solr.in.sh for SOLR_HEAP and all, but I didn't get it working. If it's only due to lack of resources on test server i.e. it'll work fine on production machine, then that'll be ok as well.

**Comment by matthijsbrouwer** [comment]
Is it possible to reproduce the error? How do you stop and (re)start Solr exactly? Do you only use the provided examples, or do you add significantly more/other documents to the index. And how much memory is available to your docker image?

If no SOLR_HEAP is defined, probably a default of 512MB is used by Solr, so this should be at least available. On my local machine everything seems to work ok with 2GB allocated to docker and with no special settings SOLR_HEAP. 

We don't have any experience with using the docker image for indexing/querying larger sets of documents. For our production indexes on machines running mostly ubuntu, we increase memory available to Solr in _/etc/default/solr.in.sh_ using _SOLR_HEAP_ and restart with _service solr restart_. This seems to work without any memory problems, we currently use indexes for a production environment with a total size of over 1TB on a machine with around 70GB memory assigned to Solr. Creating/updating these indexes is done on other machines with around 20GB available for Solr.
