### ISSUE TITLE
KWIC search results pagination

### ISSUE THREAD

**Issue by mwasiluk** [meertensinstituut/mtas#11]
Hello,

Is there maybe any builtin way to do KWIC search result pagination (with solr) on the token hit level (not on the document level). I couldn't find any examples in the docs. 

Thanks!

**Comment by matthijsbrouwer** [comment]
Yes, this is possible , see documentation on [list](https://meertensinstituut.github.io/mtas/search_component_list.html). 

To search for `[pos="ADJ"][pos="N"]`, a Solr query like

`q=title:keyword&mtas=true&mtas.list=true&mtas.list.0.field=text&mtas.list.0.query.type=cql&mtas.list.0.query.value=[pos="ADJ"][pos="N"]&mtas.list.0.key=example&mtas.list.0.prefix=t,pos,s&mtas.list.0.output=token&mtas.list.0.number=2&mtas.list.0.start=0&mtas.list.0.left=0&mtas.list.0.right=0&rows=0&wt=json&indent=true`

can be used, resulting in something like listed below. The `start` and `number` parameter can be used for pagination of the hits. The reference to the document can be found in the documentKey.

```
"mtas":{
    "list":[{
        "key":"example",
        "number":2,
        "list":[{
            "documentKey":"44e5620c-011c-11e4-b0ff-51bcbd7c379f",
            "documentHitPosition":0,
            "documentHitTotal":239,
            "documentMinPosition":0,
            "documentMaxPosition":6385,
            "startPosition":29,
            "endPosition":30,
            "tokens":[{
                "mtasId":191,
                "prefix":"t",
                "value":"beknopte",
                "positionStart":29,
                "positionEnd":29,
                "parentMtasId":337},
              {
                "mtasId":197,
                "prefix":"pos",
                "value":"ADJ",
                "positionStart":29,
                "positionEnd":29},
              {
                "mtasId":199,
                "prefix":"t",
                "value":"levensschets",
                "positionStart":30,
                "positionEnd":30,
                "parentMtasId":337},
              {
                "mtasId":204,
                "prefix":"pos",
                "value":"N",
                "positionStart":30,
                "positionEnd":30},
              {
                "mtasId":337,
                "prefix":"s",
                "value":"",
                "positionStart":7,
                "positionEnd":49,
                "parentMtasId":1152}]},
          {
            "documentKey":"44e5620c-011c-11e4-b0ff-51bcbd7c379f",
            "documentHitPosition":1,
            "documentHitTotal":239,
            "documentMinPosition":0,
            "documentMaxPosition":6385,
            "startPosition":56,
            "endPosition":57,
            "tokens":[{
                "mtasId":380,
                "prefix":"t",
                "value":"gebied",
                "positionStart":57,
                "positionEnd":57,
                "parentMtasId":610},
              {
                "mtasId":387,
                "prefix":"pos",
                "value":"N",
                "positionStart":57,
                "positionEnd":57},
              {
                "mtasId":373,
                "prefix":"t",
                "value":"velerlei",
                "positionStart":56,
                "positionEnd":56,
                "parentMtasId":610},
              {
                "mtasId":378,
                "prefix":"pos",
                "value":"ADJ",
                "positionStart":56,
                "positionEnd":56},
              {
                "mtasId":610,
                "prefix":"s",
                "value":"",
                "positionStart":50,
                "positionEnd":90,
                "parentMtasId":1152}]}]}]}
```

**Comment by mwasiluk** [comment]
Thanks! Is it possible with KWIC query (instead of list)?

**Comment by matthijsbrouwer** [comment]
With the [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html) option, KWIC results are produced for each of the listed selection of documents from the query. The start and number option restricts the number of KWIC results for each document. So, if your solr query only get the first 10 matching documents, the  [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html) option will only give you the in these 10 documents.

With the [list](https://meertensinstituut.github.io/mtas/search_component_list.html) option, a single full list KWIC results is produced for all hits occurring in documents matching the query. Here the start and number can be used for pagination of this full list.

Apart from being applied to each of the listed documents or resulting in a single list for all matching documents, both [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html)  and [list](https://meertensinstituut.github.io/mtas/search_component_list.html) are very similar in behaviour.
