### ISSUE TITLE
KWIC / list search result sorting by document metadata

### ISSUE THREAD

**Issue by mwasiluk** [meertensinstituut/mtas#12]
Hello,

Is KWIC / list results sorting supported by mtas? 
We have tried to do it with the 'sort' param, but it seems that mtas kwic ignores this parameter (only the document list is returned in the sorted order). 

Great project BTW.

Thanks.

**Comment by matthijsbrouwer** [comment]
No, the solr sort parameter only defines the order for the docList, and therefore influences the order of results in the mtas [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html) output. The mtas [list](https://meertensinstituut.github.io/mtas/search_component_list.html) completely ignores the solr sort parameter, and just iterates the hits for all documents in the docSet.

To do some kind of sorting on the kwic/list result, with [group](https://meertensinstituut.github.io/mtas/search_component_group.html) the hits can be grouped: these groupings are sorted descending by number of hits, but this is of course limited.

Do you have specific requirements on sorting a list of kwic? Do you for example want to sort the documents related to the hits for the list using [solr sort](https://wiki.apache.org/solr/CommonQueryParameters#sort), or are you more interested in sorting the hits themself?

**Comment by mwasiluk** [comment]
Thanks. We need the list of kwic hits to be sorted in relation to the returned document order (sorted by solr document field). 
We have tested mtas [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html) result sorting with solr sort, but the order of returned hits seems to be unrelated to returned docList.

**Comment by matthijsbrouwer** [comment]
If you use [kwic](https://meertensinstituut.github.io/mtas/search_component_kwic.html), for example

`fq={!mtas_cql field="text" query="[pos=\"ADJ\"][pos=\"N\"]"}&q=*:*&mtas=true&mtas.kwic=true&mtas.kwic.0.field=text&mtas.kwic.0.query.type=cql&mtas.kwic.0.query.value=[pos=\"ADJ\"][pos=\"N\"]&mtas.kwic.0.key=test&mtas.kwic.0.prefix=t,pos,s&mtas.kwic.0.output=hit&mtas.kwic.0.number=2&mtas.kwic.0.start=0&mtas.kwic.0.left=0&mtas.kwic.0.right=0&fl=id&start=0&rows=3&wt=json&indent=true&sort=title DESC`

the `response` contains the `docs` sorted descending by title, and the `kwic` contains the hits for these documents. Here the set of documents in the kwic output is not necessarily in the order as defined by sort in the solr request, but the documentKey refers to the unique key of the corresponding document in the correctly sorted response.

```
  "response":{"numFound":1684777,"start":0,"docs":[
      {
        "id":"61d2c0e1-979d-4b44-9e28-a273cc043034"},
      {
        "id":"61d2c2df-47e6-442b-80d6-cd6e67168cbe"},
      {
        "id":"61d2a1b3-9068-4815-ba4d-3370e5a809d7"}]
  },
  "mtas":{
    "kwic":[{
        "key":"adjective+noun",
        "list":[{
            "documentKey":"61d2a1b3-9068-4815-ba4d-3370e5a809d7",
            "documentTotal":31,
            "documentMinPosition":0,
            "documentMaxPosition":673,
            "list":[{
                "hit":{
                  "0":[["s",
                      null],
                    ["t",
                      "Nieuw"],
                    ["pos",
                      "ADJ"]],
                  "1":[["t",
                      "fusiebedrijf"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}},
              {
                "hit":{
                  "5":[["t",
                      "Belgische"],
                    ["pos",
                      "ADJ"],
                    ["s",
                      null]],
                  "6":[["t",
                      "energiemarkt"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}}]},
          {
            "documentKey":"61d2c0e1-979d-4b44-9e28-a273cc043034",
            "documentTotal":3,
            "documentMinPosition":0,
            "documentMaxPosition":104,
            "list":[{
                "hit":{
                  "6":[["t",
                      "Oostenrijkse"],
                    ["pos",
                      "ADJ"],
                    ["s",
                      null]],
                  "7":[["t",
                      "televisie"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}},
              {
                "hit":{
                  "27":[["t",
                      "tienjarige"],
                    ["pos",
                      "ADJ"],
                    ["s",
                      null]],
                  "28":[["t",
                      "leeftijd"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}}]},
          {
            "documentKey":"61d2c2df-47e6-442b-80d6-cd6e67168cbe",
            "documentTotal":3,
            "documentMinPosition":0,
            "documentMaxPosition":67,
            "list":[{
                "hit":{
                  "17":[["t",
                      "eige"],
                    ["pos",
                      "ADJ"],
                    ["s",
                      null]],
                  "18":[["t",
                      "denke!als"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}},
              {
                "hit":{
                  "32":[["t",
                      "aant"],
                    ["pos",
                      "ADJ"],
                    ["s",
                      null]],
                  "33":[["t",
                      "lijntje"],
                    ["pos",
                      "N"],
                    ["s",
                      null]]}}]}]}]}
```
