### ISSUE TITLE
Queries with variables without provided value

### ISSUE THREAD

**Issue by mwasiluk** [meertensinstituut/mtas#13]
Hello,

Is it possible to use variables in queries without providing their values? 
It should allow for searching for tokens with same prefix values, for example:

`[number=$1][number=$1]`

This kind of queries is supported in [national corpus of polish poliqarp search engine](http://nkjp.pl/poliqarp).

Thanks.

**Comment by matthijsbrouwer** [comment]
No, this is currently not supported, but this is one of the features we would like to add later on. Implementation for prefixes/attributes with a low number of occurring values will probably be relatively easy by applying query expansion; but if the number of  values is higher, an index extension is probably better to guarantee some performance.
