### ISSUE TITLE
Cannot test for multiple values in multi-position-expression

### ISSUE THREAD

**Issue by reckart** [meertensinstituut/mtas#14]
I can do a query like 

```
[A="value" & B="value]
```

However, it is not possible to do a query

```
<A="value" & B="value/>
```

It seems like this is an unnecessary restriction.

**Comment by matthijsbrouwer** [comment]
You can do

``<A="value"/> within <B="value"/>``

or

``<A="value"/> containing <B="value"/>``

or even 

``(<A="value"/> containing <B="value"/>) within <B="value"/>``

With `<A="value" & B="value"/>` I'm not sure it is clear which of these options is required, therefore for now we choose to not support it.

**Comment by reckart** [comment]
In my view, the semantics of `<A="value" & B="value/>` would be correspond to `<A="value"/> fullyalignedwith <B="value"/>`.

Although, to be honest, I **would** actually have an additional expectation and that entails a different question yet: https://github.com/meertensinstituut/mtas/issues/15

**Comment by matthijsbrouwer** [comment]
I think you're right and have put it on my to-do list for a new release.

**Comment by reckart** [comment]
@matthijsbrouwer would you mind keeping this issue open until it is actually resolved? That would help me react (e.g. update our dependencies) when it is done.
